server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: EXAMINATION-SERVICE
          uri: lb://EXAMINATION-SERVICE
          predicates:
            - Path=/examination/**


